# Download and importing packages for the project

In [1]:
!pip install reportlab

Collecting reportlab
  Downloading reportlab-5.0.0-py3-none-any.whl.metadata (1.6 kB)
Requirement already satisfied: pillow>=9.0.0 in /usr/local/lib/python3.12/dist-packages (from reportlab) (11.3.0)
Requirement already satisfied: charset-normalizer in /usr/local/lib/python3.12/dist-packages (from reportlab) (3.4.7)
Downloading reportlab-5.0.0-py3-none-any.whl (2.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 54.1 MB/s eta 0:00:00
Installing collected packages: reportlab
Successfully installed reportlab-5.0.0

In [2]:
# Linking Google Drive

from google.colab import drive

In [3]:
import numpy as np
import pandas as pd

from reportlab.lib.pagesizes import landscape, A4
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont

# Reading and Exploring the Excel File

In [4]:
df = pd.read_excel("/content/drive/MyDrive/CRA - Project 01/Lesson 20 - Python Certificate Generator Project/dataset.xlsx")

In [5]:
df

                  Name                 Course   CourseLevel       Date
0   Christy Cunningham                 Python      Beginner 2023-09-10
1       Douglas Tucker                 PYTHON       MASTER  2023-09-11
2       Travis Walters                   Java  Intermediate 2023-09-12
3     Nathaniel Harris        Web Development      Advanced 2023-09-13
4                    -                    NaN      Advanced        NaT
5         Tonya Carter  AI & Machine Learning      Beginner 2023-09-14
6           Erik Smith     Mobile Development      Beginner 2023-09-15
7   Kristopher Johnson                 Python      Beginner 2023-09-16
8      Jonathan Bucker                    NaN           NaN        NaT
9          Robert Buck                 PYTHON       Master  2023-09-17
10     Joseph Mcdonald                   Java  Intermediate 2023-09-18
11       Jerome Abbott        Web Development      Advanced 2023-09-19
12       William Riley  AI & Machine Learning      Beginner 2023-09-20

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         13 non-null     object
 1   Course       11 non-null     object
 2   CourseLevel  12 non-null     object
 3   Date         11 non-null     datetime64[ns]
dtypes: datetime64[ns](1), object(3)
memory usage: 548.0+ bytes

# Data Cleansing (Data Analysis)
Data cleansing - Format the date before
* deal with missing data
*

3 problems with the dataset
1. Capitalize in Course and CourseLevel
2. Date Format
3. Empty Rows

In [7]:
# Solve Problem #3 first - Drop all rows with at least one empty columns
# this will be applied to row 4 and row 8

df = df.dropna() # df =  will refresh the dataset

df

                  Name                 Course   CourseLevel       Date
0   Christy Cunningham                 Python      Beginner 2023-09-10
1       Douglas Tucker                 PYTHON       MASTER  2023-09-11
2       Travis Walters                   Java  Intermediate 2023-09-12
3     Nathaniel Harris        Web Development      Advanced 2023-09-13
5         Tonya Carter  AI & Machine Learning      Beginner 2023-09-14
6           Erik Smith     Mobile Development      Beginner 2023-09-15
7   Kristopher Johnson                 Python      Beginner 2023-09-16
9          Robert Buck                 PYTHON       Master  2023-09-17
10     Joseph Mcdonald                   Java  Intermediate 2023-09-18
11       Jerome Abbott        Web Development      Advanced 2023-09-19
12       William Riley  AI & Machine Learning      Beginner 2023-09-20

In [8]:
# Solve #2 which is data format - to format as dd/mm/yyyy

df['Date']

0    2023-09-10
1    2023-09-11
2    2023-09-12
3    2023-09-13
5    2023-09-14
6    2023-09-15
7    2023-09-16
9    2023-09-17
10   2023-09-18
11   2023-09-19
12   2023-09-20
Name: Date, dtype: datetime64[ns]

In [9]:
df['Date'].iloc[0] #iloc = indezx location

Timestamp('2023-09-10 00:00:00')

In [10]:
# Create a new column for formatted date and drop the old date column

df["Formatted_Date"] = df["Date"].dt.strftime("%d/%m/%Y") #strftime = string formatted time

# Y --> 2023
# y --> 23


df

/tmp/ipykernel_1238/3755541275.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Formatted_Date"] = df["Date"].dt.strftime("%d/%m/%Y") #strftime = string formatted time

,Name,Course,CourseLevel,Date,Formatted_Date
0,Christy Cunningham,Python,Beginner,2023-09-10,10/09/2023
1,Douglas Tucker,PYTHON,MASTER,2023-09-11,11/09/2023
2,Travis Walters,Java,Intermediate,2023-09-12,12/09/2023
3,Nathaniel Harris,Web Development,Advanced,2023-09-13,13/09/2023
5,Tonya Carter,AI & Machine Learning,Beginner,2023-09-14,14/09/2023
6,Erik Smith,Mobile Development,Beginner,2023-09-15,15/09/2023
7,Kristopher Johnson,Python,Beginner,2023-09-16,16/09/2023
9,Robert Buck,PYTHON,Master,2023-09-17,17/09/2023
10,Joseph Mcdonald,Java,Intermediate,2023-09-18,18/09/2023
11,Jerome Abbott,Web Development,Advanced,2023-09-19,19/09/2023
12,William Riley,AI & Machine Learning,Beginner,2023-09-20,20/09/2023

In [11]:
df["Formatted_Date"].dtype # for checking purpose 0 = object means strings in tables

dtype('O')

In [12]:
df.head()

,Name,Course,CourseLevel,Date,Formatted_Date
0,Christy Cunningham,Python,Beginner,2023-09-10,10/09/2023
1,Douglas Tucker,PYTHON,MASTER,2023-09-11,11/09/2023
2,Travis Walters,Java,Intermediate,2023-09-12,12/09/2023
3,Nathaniel Harris,Web Development,Advanced,2023-09-13,13/09/2023
5,Tonya Carter,AI & Machine Learning,Beginner,2023-09-14,14/09/2023

In [13]:
# Now remove the unwanted date column

df = df.drop('Date', axis = 1)

# Axis = 0 rows, Axis = 1 refers column

In [14]:
df

                  Name                 Course   CourseLevel Formatted_Date
0   Christy Cunningham                 Python      Beginner     10/09/2023
1       Douglas Tucker                 PYTHON       MASTER      11/09/2023
2       Travis Walters                   Java  Intermediate     12/09/2023
3     Nathaniel Harris        Web Development      Advanced     13/09/2023
5         Tonya Carter  AI & Machine Learning      Beginner     14/09/2023
6           Erik Smith     Mobile Development      Beginner     15/09/2023
7   Kristopher Johnson                 Python      Beginner     16/09/2023
9          Robert Buck                 PYTHON       Master      17/09/2023
10     Joseph Mcdonald                   Java  Intermediate     18/09/2023
11       Jerome Abbott        Web Development      Advanced     19/09/2023
12       William Riley  AI & Machine Learning      Beginner     20/09/2023

In [15]:
# Problem 1: Inconsistency formatting in "Course" & "CourseLevel"
# In order to format string, you can access "str" in Pandas

df["Course"] = df["Course"].str.capitalize()
df["CourseLevel"] = df["CourseLevel"].str.capitalize()

# Broadcasting function - Broadcasting the logic of capitalization to all the rows in "Course" and "CourseLevel" column
df.head()

                 Name                 Course   CourseLevel Formatted_Date
0  Christy Cunningham                 Python      Beginner     10/09/2023
1      Douglas Tucker                 Python       Master      11/09/2023
2      Travis Walters                   Java  Intermediate     12/09/2023
3    Nathaniel Harris        Web development      Advanced     13/09/2023
5        Tonya Carter  Ai & machine learning      Beginner     14/09/2023

In [16]:
# Defining the path to the fonts folder (like storing inside 'fonts_path' variable)
fonts_path = "/content/drive/MyDrive/CRA - Project 01/Lesson 20 - Python Certificate Generator Project/fonts"

In [17]:
# Register 2 fonts into project

pdfmetrics.registerFont(TTFont('Lora-Bold', fonts_path + "/Lora-Bold.ttf"))
pdfmetrics.registerFont(TTFont('Lora-Regular', fonts_path + "/Lora-Regular.ttf"))

# pdfmetrics is one of the packages we imported! This package is used to register fonts so that we can use it with pdf files.
# one of the commands in pdfmetrics is registerfont()
# TTFont() is another package we imported. And it needs 2 input:
# 1. What font are you registering?
# 2. Where is the file of the font?

Create the Certificate Logic Function

In [18]:
def certificate_generator(Name, Course, CourseLevel, Formatted_Date):

# store the generated certificate in a folder

# must be indented

  pdf_file_name = "/content/drive/MyDrive/CRA - Project 01/Lesson 20 - Python Certificate Generator Project/certificates" + Name + "-" + Course + "-" + CourseLevel + ".pdf"


# Expected output later: Christy Cunningham-Python_Beginner.pdf


# Function 1
# Canvas = Blank screen (A4 Landscape Size)
# We are storing the canvas inside pdf file
# Canvas() will need 2 inputs: -
# - 1st input: Where are you storing it?
# - 2nd input: What size?


# Ensure te below under same cell since the "def" function is here

# must be indented

  c =  canvas.Canvas(pdf_file_name, pagesize = landscape(A4))


# Function 2
# DrawImage
# Need 5 inputs
# Input 1: What are you drawing on the empty canvas
# Input 2: x-axis (coordinate 0)
# Input 3: y-axis (coordinate 0)
# Input 4: Width -> A4[1] --> Landscape for Width >  Height, if Potrait Height > Width
# Input 5: Height -> A4[0]


  template = "/content/drive/MyDrive/CRA - Project 01/Lesson 20 - Python Certificate Generator Project/certificate_template.jpg"


  c.drawImage(template, 0, 0, A4[1], A4[0]) # drawing our certificate template into our canvas

  c.save() # save the canvas

In [19]:
# Our function needs 4 input --> Name, Course, CourseLevel, Formatted_Date

certificate_generator("Sarah", "Python", "Beginner","02/07/2026")
certificate_generator("Jun", "Web Development", "Advanced","02/07/2026")

Version 2 of the Function

In [20]:
def certificate_generator(Name, Course, CourseLevel, Formatted_Date):

  pdf_file_name = "/content/drive/MyDrive/CRA - Project 01/Lesson 20 - Python Certificate Generator Project/certificates" + Name + "-" + Course + "-" + CourseLevel + ".pdf"

  c =  canvas.Canvas(pdf_file_name, pagesize = landscape(A4))

  template = "/content/drive/MyDrive/CRA - Project 01/Lesson 20 - Python Certificate Generator Project/certificate_template.jpg"

  c.drawImage(template, 0, 0, A4[1], A4[0]) # drawing our certificate template into our canvas

# Up to this point, we have an empty A4 landscape

# Find the middle of the A4 page (width)

  center_x = c._pagesize[0] / 2

  print("Full Width of the A4:  ", c._pagesize[0])
  print("Center of the A4 (x-axis): ", center_x)

# Find the middle of the A4 page (height)

  center_y = c._pagesize[1] / 2

  print("--------------------------------------------------")

  print("Full Hright of the A4:  ", c._pagesize[1])
  print("Center of the A4 (y-axis): ", center_y)


  c.save()

# Need to call out the function again since all the variables already defined in the function

certificate_generator("Sarah", "Python", "Beginner","02/07/2026")

Full Width of the A4:   841.8897637795277
Center of the A4 (x-axis):  420.94488188976385
--------------------------------------------------
Full Hright of the A4:   595.2755905511812
Center of the A4 (y-axis):  297.6377952755906

Version 3 of the Function

.setFont()
1. font type
2. font size (in pixel)

.drawCentredString()
1. x axis draw
2. y axis draw
3. whata re youn drawing

In [21]:
def certificate_generator(Name, Course, CourseLevel, Formatted_Date):

  pdf_file_name = "/content/drive/MyDrive/CRA - Project 01/Lesson 20 - Python Certificate Generator Project/certificates" + Name + "-" + Course + "-" + CourseLevel + ".pdf"

  c =  canvas.Canvas(pdf_file_name, pagesize = landscape(A4))

  template = "/content/drive/MyDrive/CRA - Project 01/Lesson 20 - Python Certificate Generator Project/certificate_template.jpg"

  c.drawImage(template, 0, 0, A4[1], A4[0])

  center_x = c._pagesize[0] / 2
  center_y = c._pagesize[1] / 2

  #1. Name
  c.setFont("Lora-Bold", 30)
  c.drawCentredString(center_x, center_y - 46, Name)

  #2. Course, CourseLevel
  c.setFont("Lora-Bold", 28)
  c.drawCentredString(center_x, center_y - 105, Course + " - " + CourseLevel)

  #3. Formatted_Date
  c.setFont("Lora-Bold", 17)
  c.drawCentredString(center_x + 190, center_y - 160, Formatted_Date)

  #4. Cert ID
  cert_id = "Cert ID: " + str(pd.Timestamp.now().timestamp()).replace(".","") # generating unique I based on current timestamp and later remove the dots to look better

  c.setFont("Lora-Bold", 12)
  c.drawCentredString(center_x + 266, center_y - 230, cert_id.upper())

  c.save()


certificate_generator("Sarah", "Python", "Beginner","02/07/2026")

In [22]:
# For Cert ID, we generated the ID based on current timestamp using pd.Timestamp

print(pd.Timestamp.now())
print(pd.Timestamp.now().timestamp()) # Unix timestamp which is number of seconds since 1 Jan 1970

2026-07-16 12:28:17.503235
1784204897.503451

Version 4 of the Function

In [24]:
# Use for loop -> loop 11 times -> used function 11 times based on different 4 inputs
# Generate certificate for each row in the Dataframe (11 rows)
# Execute  function 11 times -> generate 11 certs

# Recap: Loop through an array for loop

for x in ["Jun", "The", "Duck"]:
  print(x)

print("---------------------------------------------")

# Recap: enumerate() keeps track of the inde of each item

for index, y in enumerate(["Jun", "The", "Duck"]):
  print(str(index) + " " + y)

Jun
The
Duck
---------------------------------------------
0 Jun
1 The
2 Duck

In [26]:
# loop through the df

for x in df:
  print(x)

Name
Course
CourseLevel
Formatted_Date

In [27]:
# df.iterrows gives you loopable (array-like)
# df.iterrows: gives you 2 items (index, item(row))

for index, x in df.iterrows():
  print(index)

0
1
2
3
5
6
7
9
10
11
12

In [28]:
for index, x in df.iterrows():
  print(x)
  print("----------------------------------------------------")

Name              Christy Cunningham
Course                        Python
CourseLevel                 Beginner
Formatted_Date            10/09/2023
Name: 0, dtype: object
----------------------------------------------------
Name              Douglas Tucker
Course                    Python
CourseLevel              Master
Formatted_Date        11/09/2023
Name: 1, dtype: object
----------------------------------------------------
Name              Travis Walters
Course                      Java
CourseLevel         Intermediate
Formatted_Date        12/09/2023
Name: 2, dtype: object
----------------------------------------------------
Name              Nathaniel Harris
Course             Web development
CourseLevel               Advanced
Formatted_Date          13/09/2023
Name: 3, dtype: object
----------------------------------------------------
Name                       Tonya Carter
Course            Ai & machine learning
CourseLevel                    Beginner
Formatted_Date               14/09/2023
Name: 5, dtype: object
----------------------------------------------------
Name                      Erik Smith
Course            Mobile development
CourseLevel                 Beginner
Formatted_Date            15/09/2023
Name: 6, dtype: object
----------------------------------------------------
Name              Kristopher Johnson
Course                        Python
CourseLevel                 Beginner
Formatted_Date            16/09/2023
Name: 7, dtype: object
----------------------------------------------------
Name              Robert Buck
Course                 Python
CourseLevel           Master
Formatted_Date     17/09/2023
Name: 9, dtype: object
----------------------------------------------------
Name              Joseph Mcdonald
Course                       Java
CourseLevel          Intermediate
Formatted_Date         18/09/2023
Name: 10, dtype: object
----------------------------------------------------
Name                Jerome Abbott
Course            Web development
CourseLevel              Advanced
Formatted_Date         19/09/2023
Name: 11, dtype: object
----------------------------------------------------
Name                      William Riley
Course            Ai & machine learning
CourseLevel                    Beginner
Formatted_Date               20/09/2023
Name: 12, dtype: object
----------------------------------------------------

In [32]:
for index, x in df.iterrows():
  certificate_generator(x["Name"], x["Course"], x["CourseLevel"], x["Formatted_Date"])

print(str(len(df)) + " cert gen succesfully")

11cert gen succesfully